---

- name: Check all port numbers are accessible from current host
  wait_for:
    host: sdcgigdcapmdw02
    port: "{{ item }}"
    state: started         # Port should be open
    delay: 0               # No wait before first check (sec)
    timeout: 2             # Stop checking after timeout (sec)
  ignore_errors: yes
  with_items:
    - 443
    - 80
    - 22
